/** Ten languages covered by the school chat abuse filter. */
import { HINDI_SEXUAL_MODERATION_TERMS } from './hindiSexualModerationTerms';
import { ENGLISH_SEXUAL_MODERATION_TERMS } from './englishSexualModerationTerms';

export { HINDI_SEXUAL_MODERATION_TERMS, ENGLISH_SEXUAL_MODERATION_TERMS };

export const MODERATION_LANGUAGES = [
  'en',
  'hi',
  'bho',
  'ur',
  'pa',
  'bn',
  'ta',
  'te',
  'mr',
  'gu',
] as const;

export type ModerationLanguage = (typeof MODERATION_LANGUAGES)[number];

/**
 * Top 100 most common abusive terms in Indian school chat
 * (English, Hindi/Hinglish, and other regional languages).
 */
export const TOP_ABUSIVE_TERMS: readonly string[] = [
  // English (24)
  'asshole',
  'bastard',
  'bitch',
  'bullshit',
  'crap',
  'cunt',
  'damn',
  'dick',
  'dumb',
  'fuck',
  'fucker',
  'fucking',
  'idiot',
  'kill yourself',
  'kys',
  'loser',
  'moron',
  'motherfucker',
  'pussy',
  'retard',
  'shit',
  'shut up',
  'slut',
  'stupid',
  'whore',
  // Hindi / Hinglish romanized (30)
  'bc',
  'mc',
  'bsdk',
  'bhenchod',
  'behenchod',
  'madarchod',
  'maadarchod',
  'chutiya',
  'chutia',
  'bhosdike',
  'bhosdi',
  'gandu',
  'gaandu',
  'gaand',
  'lavda',
  'lawda',
  'lund',
  'laude',
  'randi',
  'saala',
  'sala',
  'kutta',
  'kutti',
  'harami',
  'kamina',
  'ullu',
  'bevakoof',
  'nalayak',
  'mar ja',
  'teri maa',
  // Hindi Devanagari (12)
  'चूतिया',
  'भोसड़ीके',
  'मादरचोद',
  'बहनचोद',
  'हरामी',
  'गांडू',
  'लौडा',
  'लंड',
  'रंडी',
  'कुत्ता',
  'साला',
  'कमीना',
  // Tamil (8)
  'punda',
  'pundai',
  'ommala',
  'thayoli',
  'sunni',
  'myre',
  'otha',
  'loosu',
  // Telugu (7)
  'lanja',
  'modda',
  'pooku',
  'dengey',
  'bokka',
  'na kodaka',
  'lanjakodaka',
  // Bengali (5)
  'magir',
  'banchod',
  'bokachoda',
  'choda',
  'magi',
  // Punjabi (4)
  'penchod',
  'kanjar',
  'tharki',
  'paencho',
  // Urdu (4)
  'haramzada',
  'launda',
  'haramzade',
  'behanchod',
  // Marathi (3)
  'zavadya',
  'aai ghalya',
  'aai zavadya',
  // Gujarati (2)
  'haramzado',
  'ben chod',
];

/** Extended spellings and regional variants beyond the top 100. */
export const ABUSIVE_TERMS_BY_LANGUAGE: Record<ModerationLanguage, readonly string[]> = {
  en: [
    ...ENGLISH_SEXUAL_MODERATION_TERMS,
    'bloody hell',
    'bully',
    'douche',
    'go die',
    'gtfo',
    'hate you',
    'mf',
    'mofo',
    'piss off',
    'pos',
    'stfu',
    'suck my',
    'twat',
    'ugly',
    'worthless',
    'you suck',
    'wanker',
    'dipshit',
    'jackass',
    'scumbag',
  ],
  hi: [
    ...HINDI_SEXUAL_MODERATION_TERMS,
    'bhen chod',
    'behen chod',
    'bhosdi ke',
    'bhosdiwale',
    'chut',
    'choot',
    'chootiya',
    'gand',
    'haramkhor',
    'kameena',
    'kutte',
    'loda',
    'maadarchod',
    'saali',
    'sali',
    'tatte',
    'ghatiya',
    'kutiya',
    'bhosda',
    'mar jaa',
    'apni jaan',
    'benchod',
    'maa chod',
    'maa ke',
    'teri behen',
    'bhosda',
    'jhaant',
    'jhaatu',
    'jhatu',
    'chodu',
    'chod',
    'gand mara',
    'gaand mara',
    'suar',
    'suwar',
    'bhadwa',
    'bhadwe',
    'luchcha',
    'lucha',
    'badtameez',
    'saale',
    'behn ke lode',
    'ma ke lode',
    'chutiye',
    'chutiyapa',
    'randwa',
    'bakchod',
    'चुतिया',
    'भोसड़ी',
    'भोसडी',
    'भोसडीके',
    'बहन चोद',
    'हरामखोर',
    'गांड',
    'लौड़ा',
    'कुतिया',
    'साली',
    'उल्लू',
    'भड़वा',
    'सुअर',
    'झांट',
    'झाटू',
    'चोद',
    'चोदू',
    'रंडवा',
  ],
  bho: [
    'bhaukhal',
    'chamar',
    'chapri',
    'lauda',
    'bhauka',
    'भोसड़ी',
    'मादरचोद',
    'बहनचोद',
    'चूतिया',
    'गांडू',
    'हरामी',
    'रंडी',
    'लौड़ा',
    'कमीना',
    'कुत्ता',
    'साला',
    'मर जा',
    'मार खा',
    'भड़वा',
    'सुअर',
  ],
  ur: [
    'kameena',
    'kutti',
    'lounde',
    'kamina',
    'حرامی',
    'حرامزادہ',
    'کنجر',
    'کتا',
    'لونڈا',
    'لونڈے',
    'رندی',
    'چوتیا',
    'گانڈو',
    'لنڈ',
    'بہن چود',
    'مادر چود',
    'کمینہ',
    'بہن کے',
    'ماں کے',
  ],
  pa: [
    'bhosdike',
    'ਭੋਸੜੀ',
    'ਚੂਤੀਆ',
    'ਗਾਂਡੂ',
    'ਕੰਜਰ',
    'ਥਰਕੀ',
    'ਕਮੀਨਾ',
    'ਕੁੱਤਾ',
    'ਰੰਡੀ',
    'ਲੌਡਾ',
    'ਹਰਾਮੀ',
    'ਸਾਲਾ',
    'ਮਾਦਰਚੋਦ',
    'ਪੈਂਚੋਦ',
    'ਭੋਸੜੀਕੇ',
  ],
  bn: [
    'chudi',
    'chagol',
    'bal',
    'বোকাচোদা',
    'মাগির',
    'বাঁচোদ',
    'চুদি',
    'গাণ্ডু',
    'কুত্তা',
    'রান্ডি',
    'হারামি',
    'কমিনা',
    'সালা',
    'মাদারচোদ',
    'চোদ',
    'বাল',
    'ছাগল',
    'মাগি',
    'বোকা',
  ],
  ta: [
    'omala',
    'mayire',
    'poolu',
    'kena',
    'punda mavan',
    'ஓம்மால',
    'புண்ட',
    'புண்டை',
    'சுன்னி',
    'தாயோலி',
    'மயிரே',
    'பூலு',
    'ஓத்த',
    'லூசு',
    'கெனா',
    'புண்ட மவன்',
    'சொக்கி',
    'நாயே',
    'கழுதை',
    'புண்டா',
  ],
  te: [
    'denge',
    'puk',
    'gudda',
    'pukka',
    'దెంగే',
    'దెంగేయ్',
    'లంజ',
    'లంజకొడక',
    'మొడ్డ',
    'పూకు',
    'గుద్ద',
    'బోక్క',
    'నా కొడక',
    'పూక్క',
    'సున్ని',
    'చూటియా',
    'కుక్క',
    'రాండి',
    'హరామి',
    'సాలా',
    'కమీనా',
    'లంజా',
  ],
  mr: [
    'आई घाल्य',
    'झावड्या',
    'मादरचोद',
    'भोसडी',
    'चुतिया',
    'गांडू',
    'रंडी',
    'हरामी',
    'कमीना',
    'कुत्ता',
    'साला',
    'लौडा',
    'लंड',
    'बहनचोद',
    'उल्लू',
    'नालायक',
    'झावड्या',
    'भड़वा',
  ],
  gu: [
    'bhenchod',
    'ભેન ચોદ',
    'બહેનચોદ',
    'માદરચોદ',
    'ભોસડી',
    'ચૂતિયા',
    'ગાંડૂ',
    'રંડી',
    'હરામી',
    'કમીના',
    'કૂતરો',
    'સાલા',
    'લૌડા',
    'લંડ',
    'હરામજાદો',
    'ઉલ્લૂ',
    'ભોસડીકે',
  ],
};

function dedupeTerms(terms: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const term of terms) {
    const trimmed = term.trim();
    if (!trimmed) continue;
    const key = trimmed.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(trimmed);
  }
  return out;
}

/** Top 100 + extended regional variants (deduplicated). */
export const ABUSIVE_TERMS: readonly string[] = dedupeTerms([
  ...TOP_ABUSIVE_TERMS,
  ...Object.values(ABUSIVE_TERMS_BY_LANGUAGE).flat(),
]);
