/**
 * Top ~200 English terms for sexual, nude, and inappropriate school chat content.
 */
export const ENGLISH_SEXUAL_MODERATION_TERMS: readonly string[] = [
  // Sex / sexual acts
  'sex',
  'have sex',
  'lets have sex',
  "let's have sex",
  'wanna have sex',
  'want to have sex',
  'sex with me',
  'sex with you',
  'sex tonight',
  'sex now',
  'sex chat',
  'sex talk',
  'sex video',
  'sex tape',
  'sex pics',
  'sex photos',
  'sexual',
  'sexually',
  'intercourse',
  'make love',
  'sleep with me',
  'sleep together',
  'hook up',
  'hookup',
  'one night stand',
  'friends with benefits',
  'fwb',
  'bang me',
  'bang you',
  'screw you',
  'screw me',
  'fuck me',
  'fuck you',
  'fuck her',
  'fuck him',
  'fucking me',
  'fucking you',
  'get laid',
  'laid tonight',
  'horny',
  'turned on',
  'aroused',
  'orgasm',
  'cum',
  'cumming',
  'cuming',
  'jerk off',
  'jerkoff',
  'jack off',
  'jackoff',
  'masturbate',
  'masturbating',
  'masturbation',
  'handjob',
  'hand job',
  'blowjob',
  'blow job',
  'bj',
  'oral sex',
  'anal sex',
  'anal',
  'doggy style',
  'doggystyle',
  '69',
  'sixty nine',
  'threesome',
  'foursome',
  'orgy',
  'porn',
  'porno',
  'pornography',
  'porn video',
  'porn pic',
  'porn photo',
  'xxx',
  'x rated',
  'x-rated',
  'adult video',
  'adult content',
  'adult pic',
  'adult photo',
  'blue film',
  'hentai',
  'onlyfans',
  'only fans',
  'nsfw',
  'erotic',
  'erotica',
  'dirty talk',
  'talk dirty',
  'dirty chat',
  'naughty chat',
  'naughty pic',
  'naughty photo',
  'send nudes',
  'send nude',
  'sending nudes',
  'sext',
  'sexting',
  'sext me',
  'sexting me',
  'strip for me',
  'strip tease',
  'striptease',
  'lap dance',
  'escort',
  'call girl',
  'prostitute',
  'hooker',
  'brothel',
  'rape',
  'raping',
  'molest',
  'molesting',
  'molestation',
  'incest',
  'pedophile',
  'paedophile',
  'child porn',
  'cp',
  'underage',
  'sugar daddy',
  'sugar baby',
  // Kiss / inappropriate advances
  'kiss me',
  'kiss you',
  'kiss her',
  'kiss him',
  'kiss on lips',
  'lip kiss',
  'french kiss',
  'deep kiss',
  'tongue kiss',
  'make out',
  'making out',
  'makeout',
  'smooch',
  'smooching',
  'smooch me',
  'peck on lips',
  'suck my lips',
  'lick my lips',
  'kiss my neck',
  'neck kiss',
  'hickey',
  'love bite',
  'can i kiss',
  'wanna kiss',
  'want to kiss',
  'kiss tonight',
  // Nude / naked
  'nude',
  'nudes',
  'naked',
  'nudity',
  'nudist',
  'nude pic',
  'nude photo',
  'nude pics',
  'nude photos',
  'nude image',
  'nude images',
  'nude selfie',
  'nude video',
  'nude clip',
  'nude body',
  'nude girl',
  'nude boy',
  'naked pic',
  'naked photo',
  'naked pics',
  'naked photos',
  'naked selfie',
  'naked video',
  'naked body',
  'naked girl',
  'naked boy',
  'without clothes',
  'no clothes',
  'take off clothes',
  'remove clothes',
  'strip naked',
  'get naked',
  'go naked',
  'show me nude',
  'show me naked',
  'show your body',
  'show your boobs',
  'show your tits',
  'show your ass',
  'show your pussy',
  'show your dick',
  'send your nudes',
  'send me nudes',
  'send naked',
  'send nude pic',
  'send nude photo',
  'share nudes',
  'share nude',
  'leaked nudes',
  'leaked pics',
  'private pic',
  'private photo',
  'private video',
  'intimate pic',
  'intimate photo',
  'intimate video',
  'explicit pic',
  'explicit photo',
  'explicit video',
  'explicit content',
  'inappropriate pic',
  'inappropriate photo',
  'inappropriate video',
  'sexy pic',
  'sexy photo',
  'sexy pics',
  'sexy photos',
  'sexy video',
  'sexy selfie',
  'hot pic',
  'hot photo',
  'hot pics',
  'hot photos',
  'hot video',
  'hot selfie',
  'bikini pic',
  'lingerie pic',
  'underwear pic',
  'bra pic',
  'panty pic',
  'changing room',
  'shower pic',
  'bathroom pic',
  'bedroom pic',
  'bed pic',
  'mirror selfie nude',
  'full body nude',
  'topless',
  'topless pic',
  'topless photo',
  'bottomless',
  'flash me',
  'flash your',
  'expose yourself',
  'strip pic',
  // Body parts — vulgar
  'boobs',
  'boobies',
  'tits',
  'titties',
  'breasts nude',
  'nipple',
  'nipples',
  'pussy',
  'vagina',
  'vajayjay',
  'clit',
  'clitoris',
  'dick',
  'cock',
  'penis',
  'balls',
  'testicles',
  'ass nude',
  'butt naked',
  'butthole',
  'anus',
  'boner',
  'erection',
  'wet dream',
  'camel toe',
  'muff',
  'snatch',
  'twat',
  'cunt',
  'slut',
  'whore',
  'skank',
  'tramp',
  'hoe',
  'thot',
  'simp for me',
  'send bob',
  'send vegana',
  'open cloth',
  'open robe',
];
