/**
 * Top ~200 Hindi / Hinglish terms for sexual, nude, and inappropriate chat content.
 * Romanized spellings + Devanagari. Used for school chat moderation only.
 */
export const HINDI_SEXUAL_MODERATION_TERMS: readonly string[] = [
  // Sex / sexual acts (romanized)
  'sex',
  'seks',
  'chudai',
  'chudna',
  'chudwana',
  'chudwa',
  'chudwao',
  'chodna',
  'chodne',
  'chudayi',
  'chudwane',
  'chudwayega',
  'chudwaunga',
  'chud gaya',
  'chud gayi',
  'chudwa diya',
  'chudakkad',
  'chudakad',
  'chod de',
  'chod dal',
  'chudai kar',
  'sex karo',
  'sex kar',
  'sex chahiye',
  'sex chat',
  'sex video',
  'sexy pic',
  'sexy photo',
  'sexy video',
  'muth',
  'muth marna',
  'muth mar',
  'muth maar',
  'hilana',
  'hila de',
  'hilaana',
  'tharki',
  'tharak',
  'kaamuk',
  'kaamvasna',
  'vasna',
  'sambhog',
  'sangam',
  'maithun',
  'vyabhichar',
  'gandi baat',
  'gandi baatein',
  'dirty talk',
  'hookup',
  'randibaazi',
  'randi baazi',
  'blue film',
  'porn',
  'porno',
  'xxx',
  'adult video',
  'gandi chat',
  'chusna',
  'chus le',
  'chus',
  'lund chus',
  'lauda chus',
  'gand mara',
  'gaand mara',
  'gand marna',
  'gaand marna',
  'chut maar',
  'chut mar',
  'chut phad',
  'chut phaad',
  'hastmaithun',
  'hastmaithun kar',
  'one night stand',
  'call girl',
  'escort service',
  'rangreli',
  'rangreliya',
  'kaam karna',
  'bed pe aa',
  'bed room',
  'nude chat',
  'hot pic',
  'hot photo',
  'hot video',
  'nude video',
  'nangi video',
  'without clothes',
  'kapde mat pehno',
  // Kiss / inappropriate advances (romanized)
  'kiss',
  'kiss me',
  'kiss kar',
  'kiss karo',
  'kis kar',
  'chumna',
  'chumma',
  'chum le',
  'chum lo',
  'chumban',
  'hont chato',
  'honth chato',
  'lip kiss',
  'smooch',
  'smooching',
  'chumma chati',
  'lip lock',
  'french kiss',
  // Nude / naked (romanized)
  'nanga',
  'nangi',
  'nude',
  'naked',
  'nagna',
  'nagn',
  'kapde utaro',
  'kapde khol',
  'kapde utar',
  'nange photo',
  'nude pic',
  'nude photo',
  'nangi photo',
  'nangi pic',
  'nangi ho ja',
  'nanga kar',
  'nanga dekh',
  'nangi dekh',
  'nude bhej',
  'nangi bhej',
  'nangi tasveer',
  'nange tasveer',
  'nude tasveer',
  'nangi dikha',
  'nanga dikha',
  'nangi dikhao',
  'nude dikhao',
  'nangi clip',
  'nude clip',
  'nangi film',
  'nude film',
  'nanga badan',
  'nangi body',
  'nude body',
  'nangi ladki',
  'nanga ladka',
  // Body parts — vulgar (romanized)
  'chuchi',
  'chuchiyan',
  'chuchiyon',
  'mammey',
  'boobs',
  'nipple',
  'nipples',
  'jism',
  'nanga jism',
  // Sex / sexual (Devanagari)
  'सेक्स',
  'चुदाई',
  'चोदना',
  'चुदवाना',
  'चुदना',
  'चोद दे',
  'चोद डाल',
  'चुदाई कर',
  'सेक्स करो',
  'सेक्स कर',
  'सेक्स चाहिए',
  'सेक्स चैट',
  'सेक्स वीडियो',
  'सेक्सी फोटो',
  'सेक्सी पिक',
  'सेक्सी वीडियो',
  'मुठ',
  'मुठ मारना',
  'हिलाना',
  'हिला दे',
  'ठरकी',
  'कामुक',
  'वासना',
  'संभोग',
  'मैथुन',
  'व्यभिचार',
  'गंदी बात',
  'गंदी बातें',
  'गंदी चैट',
  'पोर्न',
  'ब्लू फिल्म',
  'अश्लील',
  'अश्लीलता',
  'यौन',
  'यौन संबंध',
  'यौनता',
  'कामोत्तेजना',
  'उत्तेजना',
  'चूसना',
  'चूस ले',
  'लंड चूस',
  'लौडा चूस',
  'गांड मार',
  'गांड मारना',
  'चूत मार',
  'चूत फाड',
  'चूत फाड़',
  'हस्तमैथुन',
  'रंडीबाजी',
  'रंगरेलिया',
  'चुदक्कड़',
  // Kiss (Devanagari)
  'किस',
  'किस कर',
  'किस करो',
  'चूमना',
  'चुम्मा',
  'चुंबन',
  'होंठ चाटो',
  'होंठ चूस',
  'स्मूच',
  'लिप किस',
  // Nude (Devanagari)
  'नंगा',
  'नंगी',
  'नग्न',
  'न्यूड',
  'कपड़े उतारो',
  'कपड़े खोल',
  'कपड़े उतार',
  'नंगे फोटो',
  'न्यूड फोटो',
  'नंगी फोटो',
  'नंगी तस्वीर',
  'न्यूड पिक',
  'नंगी वीडियो',
  'न्यूड वीडियो',
  'नंगा कर',
  'नंगी हो जा',
  'नंगा देख',
  'नंगी देख',
  'नंगी भेज',
  'न्यूड भेज',
  'नंगी दिखा',
  'नंगा दिखा',
  'नंगी दिखाओ',
  'न्यूड दिखाओ',
  'नंगा बदन',
  'नंगी तस्वीर भेज',
  'न्यूड तस्वीर',
  'नंगे वीडियो',
  // Body parts (Devanagari)
  'चूची',
  'चुचियां',
  'बूब्स',
  'निप्पल',
  'जिस्म',
];
