export const qk = {
  school: ['school'] as const,
  studentProfile: ['student', 'profile'] as const,
  today: ['student', 'today'] as const,
  peers: ['student', 'peers'] as const,
  achievements: ['student', 'achievements'] as const,
  subjects: ['subjects'] as const,
  subject: (id: string) => ['subjects', id] as const,
  homework: ['homework'] as const,
  homeworkItem: (id: string) => ['homework', id] as const,
  grades: ['grades'] as const,
  exams: ['exams'] as const,
  announcements: (audience: string) => ['announcements', audience] as const,
  threads: (audience: string) => ['threads', audience] as const,
  messages: (threadId: string) => ['messages', threadId] as const,
  directory: ['directory', 'teachers'] as const,
  // parent
  parentProfile: ['parent', 'profile'] as const,
  children: ['parent', 'children'] as const,
  childToday: (id: string) => ['parent', 'today', id] as const,
  fees: (id: string) => ['parent', 'fees', id] as const,
  ptm: ['parent', 'ptm'] as const,
  transport: (id: string) => ['parent', 'transport', id] as const,
  attendance: (id: string) => ['parent', 'attendance', id] as const,
  leave: (id: string) => ['parent', 'leave', id] as const,
};
